nameOverride: sample-app

frontend:
  image: nginx:latest
  replicas: 1
  service:
    type: ClusterIP
    port: 80

backend:
  image: ghcr.io/sample-user/sample-backend:latest
  replicas: 1
  service:
    type: ClusterIP
    port: 8080
