apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/cardiforia/task.git
    targetRevision: HEAD
    path: infrastructure
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
