mysql:
  auth:
    rootPassword: "password"
    database: "textdb"
    username: "appuser"
    password: "apppassword"
  primary:
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
    persistence:
      storageClass: "standard"
      enabled: true
      size: 8Gi
  image:
    tag: 8.0
  metrics:
    enabled: true
