apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include sample-app.fullname . }}-backend"
  labels:
    app: "{{ include sample-app.name . }}-backend"
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: "{{ include sample-app.name . }}-backend"
  template:
    metadata:
      labels:
        app: "{{ include sample-app.name . }}-backend"
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          envFrom:
            - configMapRef:
                name: "{{ include sample-app.fullname . }}-config"
