apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: mysql:8
            command: ["/bin/sh", "-c"]
            args:
              - |
                TIMESTAMP=$(date +%Y%m%d%H%M%S)
                mysqldump -h mysql -u user -p$MYSQL_PASSWORD sampledb > /backups/backup-$TIMESTAMP.sql
            env:
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: password
            volumeMounts:
              - name: backup-volume
                mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: backup-pvc
