apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-frontend-config
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        location /api/ {
            proxy_pass {{ .Values.frontend.config.backendApiUrl }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
  # You can add a simple index.html here for the Nginx frontend for testing
  # index.html: |
  #   <!DOCTYPE html>
  #   <html>
  #   <head>
  #       <title>Frontend App</title>
  #   </head>
  #   <body>
  #       <h1>Hello from Frontend!</h1>
  #       <div id="backend-response">Loading backend message...</div>
  #       <script>
  #           fetch('/api/')
  #               .then(response => response.text())
  #               .then(data => {
  #                   document.getElementById('backend-response').innerText = 'Backend says: ' + data;
  #               })
  #               .catch(error => {
  #                   document.getElementById('backend-response').innerText = 'Error fetching backend: ' + error;
  #               });
  #       </script>
  #   </body>
  #   </html>

